### ISSUE TITLE
Feature: configure what stats to send

### ISSUE THREAD

**Issue by saabeilin** [fyndiq/confluent_kafka_helpers#32]
There's quite a lot stats exposed from librdkafka via statsd. Not every installation really requires all. We could make stats easily configurable via config properties, at least "sections" like `librdkafka`, `librdkafka.broker`, `librdkafka.topic`, and `librdkafka.cgrp`.

**Comment by simonwahlgren** [comment]
@saabeilin Sounds like a good idea! I would love to refactor the whole thing, it was built in like 30 minutes :sweat_smile:
