### ISSUE TITLE
Set acks=all in producer to prevent data loss

### ISSUE THREAD

**Issue by arthurk** [fyndiq/confluent_kafka_helpers#4]
default is that only one in-sync replica acknowledges the messages, this will lead to data-loss if the master crashes. we need to set it to `acks=all` (or -1) so that all in-sync replicas (in our case 2) acknowledge the message and we guarantee that messages will not be lost as long as one in-sync replica remains

https://github.com/edenhill/librdkafka/blob/b83e531d301cce6a3f0f67ec9636c3ca42376f47/CONFIGURATION.md#topic-configuration-properties
http://kafka.apache.org/documentation/

**Comment by simonwahlgren** [comment]
@arthurk Fixed in https://github.com/fyndiq/confluent_kafka_helpers/pull/6
